### ISSUE TITLE
Template rendering fails with certain charts due to kube version

### ISSUE THREAD

**Issue by puppetjoy** [jameslikeslinux/kubecm#1]
While rendering ingress-nginx:

```
Failed on localhost:
  The command failed with exit code 1
  Error: chart requires kubeVersion: >=1.21.0-0 which is incompatible with Kubernetes v1.20.0

  Use --debug flag to render out invalid YAML
Failed on 1 target: localhost
```

We need to pass `--kube-version 1.2x.y` to the helm template render command. Nest used to do this, but I forgot why so I removed it. A challenge for this project is that we have to determine what version to render for. We can call `kubectl version -o yaml` and get the server version:

```yaml
clientVersion:
  buildDate: "2024-09-25T21:41:21Z"
  compiler: gc
  gitCommit: 6fc0a69044f1ac4c13841ec4391224a2df241460
  gitTreeState: archive
  gitVersion: v1.30.3
  goVersion: go1.23.1
  major: "1"
  minor: "30"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-12-10T11:25:06Z"
  compiler: gc
  gitCommit: 354eac776046f4268e9989b21f8d1bba06033379
  gitTreeState: clean
  gitVersion: v1.30.8
  goVersion: go1.22.9
  major: "1"
  minor: "30"
  platform: linux/arm64
```
